import { Badge, type BadgeTone } from '@shared/ui/Badge';
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@shared/ui/Card';
import { Icon } from '@shared/ui/Icon';

import type { Recommendation } from '../types/scanner.types';

/**
 * ScanRecommendations — actionable, deterministic next-steps generated by
 * the recommendation service. Designed to be consumed both by the user
 * (to plan ahead) and by the future migration planner.
 */
export interface ScanRecommendationsProps {
  readonly recommendations: readonly Recommendation[];
}

export function ScanRecommendations({
  recommendations,
}: ScanRecommendationsProps): JSX.Element {
  return (
    <Card>
      <CardHeader>
        <div>
          <CardTitle>Recommendations</CardTitle>
          <CardDescription>
            Pure rule-based suggestions. AI-driven planning runs in the next step
            and uses these as compact context.
          </CardDescription>
        </div>
        <Badge tone="info" variant="outline">
          {recommendations.length} item{recommendations.length === 1 ? '' : 's'}
        </Badge>
      </CardHeader>

      <ol className="space-y-2.5">
        {recommendations.map((rec, idx) => (
          <RecommendationRow key={rec.id} index={idx + 1} rec={rec} />
        ))}
      </ol>
    </Card>
  );
}

function RecommendationRow({
  index,
  rec,
}: {
  readonly index: number;
  readonly rec: Recommendation;
}): JSX.Element {
  return (
    <li className="flex gap-3 rounded-md border border-canvas-border bg-canvas-subtle-2/40 px-3 py-2.5">
      <span className="mt-0.5 inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-md border border-canvas-border bg-canvas-overlay font-mono text-2xs tabular-nums text-ink-subtle">
        {String(index).padStart(2, '0')}
      </span>
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2">
          <p className="text-xs font-semibold text-ink">{rec.title}</p>
          <Badge tone={priorityTone(rec.priority)} variant="soft" uppercase>
            {rec.priority}
          </Badge>
          {rec.relatedCodes && rec.relatedCodes.length > 0
            ? rec.relatedCodes.map((code) => (
                <span
                  key={code}
                  className="font-mono text-[10px] uppercase tracking-wider text-ink-faint"
                >
                  {code}
                </span>
              ))
            : null}
        </div>
        <p className="mt-1 text-xs leading-relaxed text-ink-muted">{rec.detail}</p>
      </div>
      <Icon name="sparkles" className="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent" />
    </li>
  );
}

function priorityTone(priority: Recommendation['priority']): BadgeTone {
  switch (priority) {
    case 'high':
      return 'danger';
    case 'medium':
      return 'warning';
    case 'low':
      return 'neutral';
  }
}
