/**
 * Represents the originally selected source project.
 * This project is READ-ONLY for the orchestrator. All AI changes
 * happen inside a derived GitWorkspace.
 */
export interface Project {
  /** Stable identifier generated by the orchestrator. */
  readonly id: string;
  /** Display name (defaults to folder basename). */
  readonly name: string;
  /** Absolute path on the local filesystem. */
  readonly path: string;
  /** Git remote URL if discoverable, otherwise undefined. */
  readonly remoteUrl?: string;
  /** Detected default base branch (e.g. "main"). */
  readonly baseBranch?: string;
  /** ISO timestamp of when the project was first registered. */
  readonly registeredAt: string;
  /** ISO timestamp of the most recent interaction. */
  readonly lastOpenedAt?: string;
}
